# Author: Ashutosh Kumar
# Date: 2023-09-25
# Version: 1.0

name: Github Action for Maven # The name of the workflow

on: [push] # Trigger the workflow on push events, on every commit

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu environment

    steps:
      - uses: actions/checkout@v4 # Checkout the code from the repository

      - name: Set up JDK 8 for x64 # Set up JDK 8 for 64-bit architecture
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
          architecture: x64

      - name: Run Maven clean and package # Run the Maven clean and package
        run: mvn clean package #perform both the clean and package phases of the Maven build lifecycle. This command will clean the project and then package it into a distributable format (e.g., JAR) as specified in your project's configuration.
