name: Github Action for Maven # The name of the workflow

on: [push] # Trigger the workflow on push events, on every commit

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu environment

    steps:
      - uses: actions/checkout@v4 # Checkout the code from the repository

      - name: Set up JDK 8 for x64 # Set up JDK 8 for 64-bit architecture
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
          architecture: x64

      - name: Run Maven clean install # Run the Maven clean install process
        run: mvn clean install
